basePath: /
definitions:
  services.RequestAddressGeocode:
    properties:
      lat:
        type: string
      lng:
        type: string
    type: object
  services.RequestAddressSearch:
    properties:
      query:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Api server for GeoServise
  title: GeoService
  version: "1.0"
paths:
  /api/address/geocode:
    post:
      consumes:
      - application/json
      description: return closest address to point
      parameters:
      - description: Нужно указать query(улица + дом в строке)
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/services.RequestAddressGeocode'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Неверный формат запроса
        "500":
          description: Cервис https://dadata.ru не доступен
      summary: getGeocode
      tags:
      - geocode
  /api/address/search:
    post:
      consumes:
      - application/json
      description: return address from geo
      parameters:
      - description: Нужно указать query(улица + дом в строке)
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/services.RequestAddressSearch'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Неверный формат запроса
        "500":
          description: Cервис https://dadata.ru не доступен
      summary: getAddress
      tags:
      - address
swagger: "2.0"
